[build]
  command = "npm run build"
  publish = "dist"

[dev]
  targetPort = 5173

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"