import React from 'react';
import { Link } from 'react-router-dom';
import { Phone, MapPin, Instagram, CheckCircle } from 'lucide-react';
export const Footer = () => {
    return (React.createElement("footer", { className: "bg-light-header text-white transition-colors duration-200 dark:bg-dark-header border-t border-white/10" },
        React.createElement("div", { className: "mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8" },
            React.createElement("div", { className: "grid grid-cols-1 gap-8 md:grid-cols-4" },
                " ",
                React.createElement("div", null,
                    React.createElement("div", { className: "flex items-center" },
                        React.createElement("img", { src: "/images/LogoD\u00E9pannage.webp", alt: "Le Bon Remorquage - D\u00E9pannage Auto Toulouse", className: "h-12 w-auto" })),
                    React.createElement("p", { className: "mt-4 text-sm text-gray-300" },
                        "Expert en ",
                        React.createElement("strong", null, "d\u00E9pannage auto"),
                        " et ",
                        React.createElement("strong", null, "remorquage voiture"),
                        " \u00E0 Toulouse. Service d'",
                        React.createElement("strong", null, "auto secours 24h/24"),
                        " rapide et efficace pour tout type de v\u00E9hicule."),
                    React.createElement("div", { className: "mt-6 flex space-x-4" },
                        React.createElement("a", { href: "https://www.instagram.com/lebon_remorquage/", target: "_blank", rel: "noopener noreferrer", className: "rounded-full bg-white/10 p-2 transition-colors hover:bg-light-primary dark:hover:bg-dark-primary", "aria-label": "Instagram Le Bon Remorquage" },
                            React.createElement(Instagram, { className: "h-6 w-6" })))),
                React.createElement("div", null,
                    React.createElement("h3", { className: "text-lg font-semibold border-b border-light-primary pb-2 inline-block" }, "Nos Services"),
                    React.createElement("ul", { className: "mt-4 space-y-2 text-sm text-gray-300" },
                        React.createElement("li", null,
                            React.createElement(Link, { to: "/services", className: "hover:text-light-primary transition-colors" }, "\u2022 Remorquage voiture & moto")),
                        React.createElement("li", null,
                            React.createElement(Link, { to: "/services", className: "hover:text-light-primary transition-colors" }, "\u2022 D\u00E9pannage batterie & booster")),
                        React.createElement("li", null,
                            React.createElement(Link, { to: "/services", className: "hover:text-light-primary transition-colors" }, "\u2022 Ouverture porte voiture bloqu\u00E9e")),
                        React.createElement("li", null,
                            React.createElement(Link, { to: "/services", className: "hover:text-light-primary transition-colors" }, "\u2022 Erreur carburant (vidange)")),
                        React.createElement("li", null,
                            React.createElement(Link, { to: "/services", className: "hover:text-light-primary transition-colors" }, "\u2022 Remorquage parking sous-sol")),
                        React.createElement("li", null,
                            React.createElement(Link, { to: "/services", className: "hover:text-light-primary transition-colors" }, "\u2022 Transport longue distance Europe")))),
                React.createElement("div", null,
                    React.createElement("h3", { className: "text-lg font-semibold border-b border-light-primary pb-2 inline-block" }, "Secteur 31 & 82"),
                    React.createElement("ul", { className: "mt-4 space-y-2 text-sm text-gray-300" },
                        React.createElement("li", null,
                            React.createElement(Link, { to: "/zone-intervention", className: "hover:text-light-primary transition-colors" }, "\u2022 Toulouse Centre & P\u00E9riph\u00E9rie")),
                        React.createElement("li", null,
                            React.createElement(Link, { to: "/zone-intervention", className: "hover:text-light-primary transition-colors" }, "\u2022 Blagnac, Colomiers, Muret")),
                        React.createElement("li", null,
                            React.createElement(Link, { to: "/zone-intervention", className: "hover:text-light-primary transition-colors" }, "\u2022 Balma, L'Union, Ramonville")),
                        React.createElement("li", null,
                            React.createElement(Link, { to: "/zone-intervention", className: "hover:text-light-primary transition-colors" }, "\u2022 Auto Secours Montauban (82)")),
                        React.createElement("li", null,
                            React.createElement(Link, { to: "/zone-intervention", className: "hover:text-light-primary transition-colors" }, "\u2022 Intervention Rocade & Autoroute")))),
                React.createElement("div", null,
                    React.createElement("h3", { className: "text-lg font-semibold border-b border-light-primary pb-2 inline-block" }, "Contact Urgence"),
                    React.createElement("ul", { className: "mt-4 space-y-4" },
                        React.createElement("li", { className: "flex items-center" },
                            React.createElement(Phone, { className: "mr-2 h-5 w-5 text-light-primary" }),
                            React.createElement("a", { href: "tel:0768261050", className: "text-lg font-bold hover:text-light-primary transition-colors" }, "07 68 26 10 50")),
                        React.createElement("li", { className: "flex items-start" },
                            React.createElement(MapPin, { className: "mr-2 h-5 w-5 text-light-primary mt-1" }),
                            React.createElement("span", { className: "text-sm text-gray-300" },
                                "Si\u00E8ge : 2 passage Bailly,",
                                React.createElement("br", null),
                                "31100 Toulouse")),
                        React.createElement("li", { className: "flex items-center text-sm" },
                            React.createElement(CheckCircle, { className: "mr-2 h-5 w-5 text-green-500" }),
                            React.createElement("span", { className: "text-gray-300" }, "Assistance 24/7 - Intervention < 30min"))))),
            React.createElement("div", { className: "mt-12 border-t border-gray-800 pt-8 flex flex-col md:flex-row justify-between items-center gap-4" },
                React.createElement("div", { className: "flex space-x-6 text-xs text-gray-400" },
                    React.createElement(Link, { to: "/mentions-legales", className: "hover:text-white transition-colors" }, "Mentions l\u00E9gales"),
                    React.createElement(Link, { to: "/politique-confidentialite", className: "hover:text-white transition-colors" }, "Politique de confidentialit\u00E9"),
                    React.createElement(Link, { to: "/contact", className: "hover:text-white transition-colors" }, "Demander un devis")),
                React.createElement("p", { className: "text-xs text-gray-500" },
                    "\u00A9 ",
                    new Date().getFullYear(),
                    " Le Bon Remorquage - Auto Secours Toulouse & 31.")))));
};
