import React from 'react';
import { Helmet } from 'react-helmet-async';
import { Link } from 'react-router-dom';
import { Globe, Clock, PenTool as Tool, Truck, Wrench, CheckCircle, Phone, Car, Plane as Crane, Key, Settings, Warehouse, Shield, MapPin, Umbrella, Zap, Search, HardHat } from 'lucide-react';
import { useInView } from 'react-intersection-observer';
const garagesPartenaires = [
    { nom: "Garage Central Auto", ville: "Toulouse Centre", specialites: ["Mécanique générale", "Diagnostic électronique"] },
    { nom: "Auto Service Premium", ville: "Blagnac", specialites: ["Véhicules premium", "Carrosserie"] },
    { nom: "Rapid'Auto Services", ville: "Colomiers", specialites: ["Réparation rapide", "Pneumatiques"] },
    { nom: "Garage de la Gare", ville: "Toulouse Sud", specialites: ["Toutes marques", "Climatisation"] }
];
// ✅ Liste de services exclusivement basée sur tes choix
const servicesDetaille = [
    { icon: Globe, title: "Transport de véhicule Europe", desc: "Convoyage professionnel de votre véhicule en France et partout en Europe." },
    { icon: Zap, title: "Assistance routière urgente", desc: "Intervention immédiate pour batterie HS, crevaison ou panne moteur." },
    { icon: Wrench, title: "Dépannage mécanique Toulouse", desc: "Diagnostic et réparations légères sur place pour redémarrer rapidement." },
    { icon: Truck, title: "Remorquage voiture / moto", desc: "Transport sécurisé de votre véhicule vers le garage de votre choix." },
    { icon: Crane, title: "Levage, Grutage & Treuillage", desc: "Récupération de véhicules accidentés ou enlisés avec matériel spécialisé." },
    { icon: Search, title: "Enlèvement fourrière / épave", desc: "Assistance transport pour sortie de fourrière ou enlèvement de véhicule hors d'usage." },
    { icon: Settings, title: "Réparation rapide en atelier", desc: "Prise en charge de votre véhicule dans nos ateliers partenaires pour réparations express." },
    { icon: Key, title: "Ouverture de porte & Perte de clés", desc: "Ouverture sécurisée de votre portière sans dégâts en cas d'oubli de clés." },
    { icon: HardHat, title: "Nettoyage & Detailing complet", desc: "Remise à neuf esthétique intérieure et extérieure de votre véhicule." },
    { icon: Car, title: "Estimation Achat-Revente", desc: "Service d'expertise et de conseil pour l'achat ou la revente de votre auto." }
];
const whyChooseUs = [
    { icon: Clock, title: "Intervention rapide", description: "Arrivée en moins de 30 minutes sur Toulouse.", image: "/images/Inter_rapide.webp" },
    { icon: Tool, title: "Expertise technique", description: "Techniciens qualifiés et matériel professionnel.", image: "/images/Expert_tech.webp" },
    { icon: Car, title: "Tous véhicules", description: "De la citadine au poids lourd.", image: "/images/All_car.webp" },
    { icon: Umbrella, title: "Assurance complète", description: "Véhicules et clients entièrement assurés.", image: "/images/Assurance.webp" }
];
export const HomePage = () => {
    const { ref, inView } = useInView({ triggerOnce: true, threshold: 0.1 });
    return (React.createElement(React.Fragment, null,
        React.createElement(Helmet, null,
            React.createElement("title", null, "D\u00E9pannage & Remorquage Auto Toulouse 24h/24 | Expert Auto Secours 31"),
            React.createElement("meta", { name: "description", content: "Besoin d'un d\u00E9pannage auto urgent \u00E0 Toulouse ? Arriv\u00E9e en 30 min. Remorquage voiture, moto, assistance 24j/7 et transport Europe. Devis Gratuit." })),
        React.createElement("div", { className: "relative min-h-[90vh] bg-gray-900 flex items-center" },
            React.createElement("div", { className: "absolute inset-0 bg-cover bg-center bg-no-repeat opacity-50", style: { backgroundImage: 'url("/images/hero/hero-background.jpg")' } }),
            React.createElement("div", { className: "relative mx-auto max-w-7xl px-4 py-20 text-center lg:text-left lg:flex lg:items-center lg:gap-12" },
                React.createElement("div", { className: "lg:w-2/3" },
                    React.createElement("h1", { className: "text-4xl font-extrabold tracking-tight text-white sm:text-6xl" },
                        "D\u00E9pannage & Remorquage ",
                        React.createElement("span", { className: "text-light-primary dark:text-dark-primary" }, "Toulouse")),
                    React.createElement("p", { className: "mt-6 max-w-2xl text-lg text-gray-200 sm:text-2xl font-medium" },
                        "Assistance routi\u00E8re urgente 24h/24 et 7j/7.",
                        React.createElement("span", { className: "block text-light-primary font-bold" }, "Arriv\u00E9e d'une d\u00E9panneuse en moins de 30 min.")),
                    React.createElement("div", { className: "mt-10 flex flex-col sm:flex-row gap-4 justify-center lg:justify-start" },
                        React.createElement("a", { href: "tel:0768261050", className: "flex items-center justify-center gap-3 rounded-full bg-light-primary px-8 py-4 text-xl font-bold text-white hover:bg-light-hover transition-all shadow-lg hover:scale-105" },
                            React.createElement(Phone, { className: "h-6 w-6 animate-pulse" }),
                            "07 68 26 10 50"),
                        React.createElement(Link, { to: "/contact", className: "flex items-center justify-center rounded-full border-2 border-white px-8 py-4 text-xl font-bold text-white hover:bg-white hover:text-gray-900 transition-all" }, "Devis Gratuit")),
                    React.createElement("div", { className: "mt-12 grid grid-cols-2 md:grid-cols-4 gap-4 text-white/90" },
                        React.createElement("div", { className: "flex items-center gap-2 text-sm font-semibold" },
                            React.createElement(CheckCircle, { className: "text-green-500 h-5 w-5" }),
                            " Agr\u00E9\u00E9 Assurances"),
                        React.createElement("div", { className: "flex items-center gap-2 text-sm font-semibold" },
                            React.createElement(CheckCircle, { className: "text-green-500 h-5 w-5" }),
                            " Intervention 30 min"),
                        React.createElement("div", { className: "flex items-center gap-2 text-sm font-semibold" },
                            React.createElement(CheckCircle, { className: "text-green-500 h-5 w-5" }),
                            " Devis par t\u00E9l\u00E9phone"),
                        React.createElement("div", { className: "flex items-center gap-2 text-sm font-semibold" },
                            React.createElement(CheckCircle, { className: "text-green-500 h-5 w-5" }),
                            " 7j/7 - 24h/24"))))),
        React.createElement("div", { className: "bg-white py-16 dark:bg-dark-background" },
            React.createElement("div", { className: "mx-auto max-w-7xl px-4" },
                React.createElement("div", { className: "text-center mb-16" },
                    React.createElement("h2", { className: "text-3xl font-bold text-gray-900 dark:text-white sm:text-4xl" }, "Nos Services de D\u00E9pannage"),
                    React.createElement("p", { className: "mt-4 text-lg text-gray-600 dark:text-gray-400" }, "Une solution compl\u00E8te pour votre s\u00E9r\u00E9nit\u00E9 sur la route.")),
                React.createElement("div", { className: "grid gap-8 md:grid-cols-2 lg:grid-cols-3" }, servicesDetaille.map((s, i) => (React.createElement("div", { key: i, className: "p-8 rounded-2xl bg-gray-50 dark:bg-dark-card border border-gray-100 dark:border-dark-border hover:shadow-xl transition-shadow" },
                    React.createElement(s.icon, { className: "h-12 w-12 text-light-primary mb-6" }),
                    React.createElement("h3", { className: "text-xl font-bold text-gray-900 dark:text-white mb-4" }, s.title),
                    React.createElement("p", { className: "text-gray-600 dark:text-gray-400 leading-relaxed" }, s.desc))))))),
        React.createElement("div", { className: "bg-gray-50 py-16 dark:bg-dark-background/50" },
            React.createElement("div", { className: "mx-auto max-w-7xl px-4" },
                React.createElement("h2", { className: "text-center text-3xl font-bold mb-16 dark:text-white" }, "Pourquoi choisir Le Bon Remorquage ?"),
                React.createElement("div", { className: "grid grid-cols-1 gap-8 sm:grid-cols-2 lg:grid-cols-4" }, whyChooseUs.map((item, index) => (React.createElement("div", { key: index, className: "group relative h-80 overflow-hidden rounded-2xl shadow-lg" },
                    React.createElement("div", { className: "absolute inset-0 bg-cover bg-center transition-transform group-hover:scale-110", style: { backgroundImage: `url(${item.image})` } }),
                    React.createElement("div", { className: "absolute inset-0 bg-gradient-to-t from-black/90 via-black/40 to-transparent" }),
                    React.createElement("div", { className: "relative h-full flex flex-col justify-end p-6 text-white text-center" },
                        React.createElement("div", { className: "mx-auto mb-4 bg-light-primary p-3 rounded-full" },
                            React.createElement(item.icon, { className: "h-6 w-6" })),
                        React.createElement("h3", { className: "text-xl font-bold mb-2" }, item.title),
                        React.createElement("p", { className: "text-sm opacity-90" }, item.description)))))))),
        React.createElement("div", { className: "py-16 bg-white dark:bg-dark-card transition-colors" },
            React.createElement("div", { className: "mx-auto max-w-7xl px-4" },
                React.createElement("div", { className: "relative overflow-hidden rounded-3xl bg-gradient-to-r from-gray-900 to-gray-800 dark:from-gray-800 dark:to-black text-white shadow-2xl transition-transform hover:-translate-y-1 duration-300 hover:shadow-light-primary/20" },
                    React.createElement("div", { className: "absolute top-0 right-0 -mt-10 -mr-10 h-64 w-64 rounded-full bg-light-primary opacity-20 blur-3xl pointer-events-none" }),
                    React.createElement("div", { className: "absolute bottom-0 left-0 -mb-10 -ml-10 h-48 w-48 rounded-full bg-light-primary/30 blur-2xl pointer-events-none" }),
                    React.createElement("div", { className: "relative px-8 py-12 md:p-14 flex flex-col items-center text-center md:flex-row md:text-left gap-10" },
                        React.createElement("div", { className: "flex-shrink-0 relative" },
                            React.createElement("div", { className: "absolute inset-0 bg-light-primary rounded-full blur-xl opacity-50 animate-pulse pointer-events-none" }),
                            React.createElement(Warehouse, { className: "relative h-24 w-24 text-white drop-shadow-lg" })),
                        React.createElement("div", { className: "flex-1" },
                            React.createElement("div", { className: "flex items-center justify-center md:justify-start gap-3 mb-4" },
                                React.createElement(Shield, { className: "h-8 w-8 text-light-primary flex-shrink-0" }),
                                React.createElement("h2", { className: "text-3xl font-extrabold sm:text-4xl tracking-tight" }, "Stockage S\u00E9curis\u00E9 de V\u00E9hicules")),
                            React.createElement("p", { className: "text-lg text-gray-300 leading-relaxed max-w-3xl mx-auto md:mx-0" },
                                "Votre tranquillit\u00E9 d'esprit est notre priorit\u00E9. Nous poss\u00E9dons ",
                                React.createElement("strong", { className: "text-white" }, "nos propres garages s\u00E9curis\u00E9s"),
                                " sous haute surveillance pour conserver votre v\u00E9hicule (auto, moto, utilitaire). Que ce soit suite \u00E0 un accident ou en attente d'une r\u00E9paration, votre v\u00E9hicule est stock\u00E9 \u00E0 l'abri de tous risques et des intemp\u00E9ries."),
                            React.createElement("div", { className: "mt-8 flex flex-wrap justify-center md:justify-start gap-3 sm:gap-4 text-sm font-semibold" },
                                React.createElement("div", { className: "flex items-center gap-2 bg-white/10 px-4 py-2 rounded-full border border-white/10 backdrop-blur-sm" },
                                    React.createElement(CheckCircle, { className: "h-4 w-4 text-green-400" }),
                                    " Locaux S\u00E9curis\u00E9s"),
                                React.createElement("div", { className: "flex items-center gap-2 bg-white/10 px-4 py-2 rounded-full border border-white/10 backdrop-blur-sm" },
                                    React.createElement(CheckCircle, { className: "h-4 w-4 text-green-400" }),
                                    " \u00C0 l'abri des intemp\u00E9ries"),
                                React.createElement("div", { className: "flex items-center gap-2 bg-white/10 px-4 py-2 rounded-full border border-white/10 backdrop-blur-sm" },
                                    React.createElement(CheckCircle, { className: "h-4 w-4 text-green-400" }),
                                    " Assurance garantie"))))))),
        React.createElement("div", { className: "bg-gray-50 py-16 dark:bg-dark-background/50" },
            React.createElement("div", { className: "mx-auto max-w-7xl px-4 lg:grid lg:grid-cols-2 lg:gap-16" },
                React.createElement("div", null,
                    React.createElement("h2", { className: "text-3xl font-bold mb-6 dark:text-white" }, "Intervention 50 km autour de Toulouse"),
                    React.createElement("p", { className: "text-lg text-gray-600 dark:text-gray-300 mb-8 leading-relaxed" }, "Nous couvrons l'int\u00E9gralit\u00E9 de la m\u00E9tropole toulousaine et les villes dans un rayon de **50 km**. Que vous soyez sur la **Rocade**, l'A61, A62 ou en p\u00E9riph\u00E9rie, nous intervenons rapidement."),
                    React.createElement("ul", { className: "grid grid-cols-2 gap-4 text-light-primary font-bold" },
                        React.createElement("li", { className: "flex items-center gap-2" },
                            React.createElement(MapPin, { className: "h-4 w-4" }),
                            " Toulouse Centre"),
                        React.createElement("li", { className: "flex items-center gap-2" },
                            React.createElement(MapPin, { className: "h-4 w-4" }),
                            " Blagnac / Colomiers"),
                        React.createElement("li", { className: "flex items-center gap-2" },
                            React.createElement(MapPin, { className: "h-4 w-4" }),
                            " Muret / Portet"),
                        React.createElement("li", { className: "flex items-center gap-2" },
                            React.createElement(MapPin, { className: "h-4 w-4" }),
                            " Tournefeuille / Plaisance"),
                        React.createElement("li", { className: "flex items-center gap-2" },
                            React.createElement(MapPin, { className: "h-4 w-4" }),
                            " Balma / L'Union"),
                        React.createElement("li", { className: "flex items-center gap-2" },
                            React.createElement(MapPin, { className: "h-4 w-4" }),
                            " + de 50 km alentours"))),
                React.createElement("div", { className: "mt-12 lg:mt-0" },
                    React.createElement("h2", { className: "text-2xl font-bold mb-6 dark:text-white" }, "F.A.Q D\u00E9pannage"),
                    React.createElement("div", { className: "space-y-6" },
                        React.createElement("div", null,
                            React.createElement("h4", { className: "font-bold text-gray-900 dark:text-white" }, "Comment vous contacter pour une urgence ?"),
                            React.createElement("p", { className: "text-gray-600 dark:text-gray-400 text-sm mt-2" }, "Appelez directement notre ligne d'urgence au **07 68 26 10 50**. Nous sommes joignables 24h/24 et 7j/7.")),
                        React.createElement("div", null,
                            React.createElement("h4", { className: "font-bold text-gray-900 dark:text-white" }, "O\u00F9 peut-on retrouver vos actualit\u00E9s ?"),
                            React.createElement("p", { className: "text-gray-600 dark:text-gray-400 text-sm mt-2" }, "Vous pouvez nous suivre sur Instagram **@lebon_remorquage** pour voir nos interventions en direct ou nous contacter via Snapchat et WhatsApp.")),
                        React.createElement("div", null,
                            React.createElement("h4", { className: "font-bold text-gray-900 dark:text-white" }, "Proposez-vous des devis ?"),
                            React.createElement("p", { className: "text-gray-600 dark:text-gray-400 text-sm mt-2" }, "Oui, vous pouvez obtenir un devis gratuit et personnalis\u00E9 par t\u00E9l\u00E9phone ou via notre formulaire de contact sur le site.")))))),
        React.createElement("div", { className: "bg-light-primary py-12 text-center text-white" },
            React.createElement("h2", { className: "text-3xl font-bold mb-6" }, "Besoin d'aide ? On arrive tout de suite."),
            React.createElement("a", { href: "tel:0768261050", className: "inline-flex items-center gap-3 bg-white text-light-primary px-10 py-5 rounded-full text-2xl font-black shadow-2xl hover:bg-gray-100 transition-colors" },
                React.createElement(Phone, { className: "h-8 w-8" }),
                "APPELEZ LE 07 68 26 10 50")),
        React.createElement("div", { className: "fixed bottom-6 right-6 z-50 md:hidden" },
            React.createElement("a", { href: "tel:0768261050", className: "flex h-16 w-16 items-center justify-center rounded-full bg-light-primary text-white shadow-2xl transition-transform hover:scale-110 active:scale-95 animate-bounce", "aria-label": "Appeler d\u00E9pannage urgent" },
                React.createElement(Phone, { className: "h-8 w-8" })))));
};
