import React from 'react';
import { Helmet } from 'react-helmet-async';
import { Building2, Mail, Phone, Globe, Shield, Cookie, FileText } from 'lucide-react';
export const MentionsLegalesPage = () => {
    return (React.createElement(React.Fragment, null,
        React.createElement(Helmet, null,
            React.createElement("title", null, "Mentions l\u00E9gales - Le Bon Remorquage"),
            React.createElement("meta", { name: "description", content: "Mentions l\u00E9gales du site Le Bon Remorquage. Informations sur l'\u00E9diteur, l'h\u00E9bergeur et les conditions d'utilisation du site." })),
        React.createElement("div", { className: "bg-light-background py-12 transition-colors dark:bg-dark-background" },
            React.createElement("div", { className: "mx-auto max-w-4xl px-4 sm:px-6 lg:px-8" },
                React.createElement("div", { className: "rounded-lg bg-white p-8 shadow-lg transition-colors dark:bg-dark-card" },
                    React.createElement("div", { className: "mb-8 text-center" },
                        React.createElement("h1", { className: "text-3xl font-bold text-light-text dark:text-dark-text" }, "Mentions l\u00E9gales"),
                        React.createElement("p", { className: "mt-2 text-gray-600 dark:text-gray-300" }, "www.lebonremorquage.com")),
                    React.createElement("div", { className: "prose prose-gray max-w-none dark:prose-invert" },
                        React.createElement("p", { className: "text-sm text-gray-600 dark:text-gray-400 mb-8" }, "Conform\u00E9ment \u00E0 la loi n\u00B02004-575 du 21 juin 2004 pour la confiance dans l'\u00E9conomie num\u00E9rique (LCEN), les informations suivantes sont port\u00E9es \u00E0 la connaissance des utilisateurs du site www.lebonremorquage.com :"),
                        React.createElement("div", { className: "mb-8" },
                            React.createElement("div", { className: "mb-4 flex items-center" },
                                React.createElement(Building2, { className: "mr-3 h-6 w-6 text-light-primary dark:text-dark-primary" }),
                                React.createElement("h2", { className: "text-xl font-semibold text-light-text dark:text-dark-text" }, "1. \u00C9diteur du site")),
                            React.createElement("div", { className: "ml-9 space-y-2 text-gray-700 dark:text-gray-300" },
                                React.createElement("p", null,
                                    React.createElement("strong", null, "Raison sociale :"),
                                    " LE BON REMORQUAGE"),
                                React.createElement("p", null,
                                    React.createElement("strong", null, "Forme juridique :"),
                                    " SASU \u2013 Soci\u00E9t\u00E9 par Actions Simplifi\u00E9e Unipersonnelle"),
                                React.createElement("p", null,
                                    React.createElement("strong", null, "Si\u00E8ge social :"),
                                    " Toulouse, France"),
                                React.createElement("p", null,
                                    React.createElement("strong", null, "SIRET :"),
                                    " 947 554 663 00015"),
                                React.createElement("p", null,
                                    React.createElement("strong", null, "RCS :"),
                                    " Toulouse"),
                                React.createElement("p", null,
                                    React.createElement("strong", null, "Capital social :"),
                                    " 2 000 \u20AC"),
                                React.createElement("p", null,
                                    React.createElement("strong", null, "Responsable de la publication :"),
                                    " M. Nicolas PLANELLES"),
                                React.createElement("div", { className: "flex items-center" },
                                    React.createElement(Mail, { className: "mr-2 h-4 w-4 text-light-primary dark:text-dark-primary" }),
                                    React.createElement("a", { href: "mailto:contactlebonremorquage@gmail.com", className: "text-light-primary hover:text-light-hover dark:text-dark-primary dark:hover:text-dark-hover" }, "contactlebonremorquage@gmail.com")))),
                        React.createElement("div", { className: "mb-8" },
                            React.createElement("div", { className: "mb-4 flex items-center" },
                                React.createElement(Globe, { className: "mr-3 h-6 w-6 text-light-primary dark:text-dark-primary" }),
                                React.createElement("h2", { className: "text-xl font-semibold text-light-text dark:text-dark-text" }, "2. H\u00E9bergeur")),
                            React.createElement("div", { className: "ml-9 space-y-2 text-gray-700 dark:text-gray-300" },
                                React.createElement("p", null,
                                    React.createElement("strong", null, "H\u00E9bergeur :"),
                                    " OVH SAS"),
                                React.createElement("p", null,
                                    React.createElement("strong", null, "Adresse :"),
                                    " 2 rue Kellermann \u2013 59100 Roubaix \u2013 France"),
                                React.createElement("div", { className: "flex items-center" },
                                    React.createElement(Phone, { className: "mr-2 h-4 w-4 text-light-primary dark:text-dark-primary" }),
                                    React.createElement("span", null, "1007")),
                                React.createElement("div", { className: "flex items-center" },
                                    React.createElement(Globe, { className: "mr-2 h-4 w-4 text-light-primary dark:text-dark-primary" }),
                                    React.createElement("a", { href: "https://www.ovhcloud.com", target: "_blank", rel: "noopener noreferrer", className: "text-light-primary hover:text-light-hover dark:text-dark-primary dark:hover:text-dark-hover" }, "www.ovhcloud.com")))),
                        React.createElement("div", { className: "mb-8" },
                            React.createElement("div", { className: "mb-4 flex items-center" },
                                React.createElement(FileText, { className: "mr-3 h-6 w-6 text-light-primary dark:text-dark-primary" }),
                                React.createElement("h2", { className: "text-xl font-semibold text-light-text dark:text-dark-text" }, "3. Conception et d\u00E9veloppement")),
                            React.createElement("div", { className: "ml-9 space-y-2 text-gray-700 dark:text-gray-300" },
                                React.createElement("p", null,
                                    React.createElement("strong", null, "Responsable technique :"),
                                    " Hugo-Mehdi TAJ"),
                                React.createElement("div", { className: "flex items-center" },
                                    React.createElement(Mail, { className: "mr-2 h-4 w-4 text-light-primary dark:text-dark-primary" }),
                                    React.createElement("a", { href: "mailto:hugo.mehdi197@gmail.com", className: "text-light-primary hover:text-light-hover dark:text-dark-primary dark:hover:text-dark-hover" }, "hugo.mehdi197@gmail.com")))),
                        React.createElement("div", { className: "mb-8" },
                            React.createElement("div", { className: "mb-4 flex items-center" },
                                React.createElement(Shield, { className: "mr-3 h-6 w-6 text-light-primary dark:text-dark-primary" }),
                                React.createElement("h2", { className: "text-xl font-semibold text-light-text dark:text-dark-text" }, "4. Propri\u00E9t\u00E9 intellectuelle")),
                            React.createElement("div", { className: "ml-9 text-gray-700 dark:text-gray-300" },
                                React.createElement("p", null, "Tous les contenus pr\u00E9sents sur le site (textes, images, logos, etc.) sont prot\u00E9g\u00E9s par le droit d'auteur. Toute reproduction sans autorisation est interdite."))),
                        React.createElement("div", { className: "mb-8" },
                            React.createElement("div", { className: "mb-4 flex items-center" },
                                React.createElement(Shield, { className: "mr-3 h-6 w-6 text-light-primary dark:text-dark-primary" }),
                                React.createElement("h2", { className: "text-xl font-semibold text-light-text dark:text-dark-text" }, "5. Donn\u00E9es personnelles")),
                            React.createElement("div", { className: "ml-9 space-y-3 text-gray-700 dark:text-gray-300" },
                                React.createElement("p", null, "Le site peut recueillir certaines donn\u00E9es personnelles via ses formulaires (nom, email, t\u00E9l\u00E9phone). Ces donn\u00E9es sont strictement n\u00E9cessaires au traitement des demandes."),
                                React.createElement("p", null,
                                    React.createElement("strong", null, "Le responsable du traitement est LE BON REMORQUAGE.")),
                                React.createElement("p", null, "Les donn\u00E9es ne sont ni c\u00E9d\u00E9es ni revendues, et sont conserv\u00E9es pour une dur\u00E9e conforme \u00E0 la r\u00E9glementation en vigueur."),
                                React.createElement("p", null, "Conform\u00E9ment \u00E0 la loi \u00AB Informatique et Libert\u00E9s \u00BB et au RGPD, vous pouvez exercer vos droits d'acc\u00E8s, de rectification ou de suppression en \u00E9crivant \u00E0 :"),
                                React.createElement("div", { className: "flex items-center" },
                                    React.createElement(Mail, { className: "mr-2 h-4 w-4 text-light-primary dark:text-dark-primary" }),
                                    React.createElement("a", { href: "mailto:contactlebonremorquage@gmail.com", className: "text-light-primary hover:text-light-hover dark:text-dark-primary dark:hover:text-dark-hover" }, "contactlebonremorquage@gmail.com")))),
                        React.createElement("div", { className: "mb-8" },
                            React.createElement("div", { className: "mb-4 flex items-center" },
                                React.createElement(Cookie, { className: "mr-3 h-6 w-6 text-light-primary dark:text-dark-primary" }),
                                React.createElement("h2", { className: "text-xl font-semibold text-light-text dark:text-dark-text" }, "6. Cookies")),
                            React.createElement("div", { className: "ml-9 text-gray-700 dark:text-gray-300" },
                                React.createElement("p", null, "Des cookies peuvent \u00EAtre utilis\u00E9s pour am\u00E9liorer la navigation ou mesurer l'audience. Vous pouvez les refuser via votre navigateur."))),
                        React.createElement("div", { className: "mb-8" },
                            React.createElement("div", { className: "mb-4 flex items-center" },
                                React.createElement(Mail, { className: "mr-3 h-6 w-6 text-light-primary dark:text-dark-primary" }),
                                React.createElement("h2", { className: "text-xl font-semibold text-light-text dark:text-dark-text" }, "7. Contact")),
                            React.createElement("div", { className: "ml-9 space-y-2 text-gray-700 dark:text-gray-300" },
                                React.createElement("p", null, "Pour toute question li\u00E9e au site ou \u00E0 son contenu :"),
                                React.createElement("div", { className: "flex items-center" },
                                    React.createElement(Mail, { className: "mr-2 h-4 w-4 text-light-primary dark:text-dark-primary" }),
                                    React.createElement("a", { href: "mailto:contactlebonremorquage@gmail.com", className: "text-light-primary hover:text-light-hover dark:text-dark-primary dark:hover:text-dark-hover" }, "contactlebonremorquage@gmail.com")))),
                        React.createElement("div", { className: "mt-12 border-t border-gray-200 pt-6 text-center dark:border-gray-700" },
                            React.createElement("p", { className: "text-sm text-gray-500 dark:text-gray-400" },
                                "Derni\u00E8re mise \u00E0 jour : ",
                                new Date().toLocaleDateString('fr-FR')))))))));
};
